### ISSUE TITLE
Ember and Atheneum

### ISSUE THREAD

**Issue by magick93** [AtheneumChain/Atheneum#11]
Hi

I'm interested to know if Ember and Atheneum use same blockchain?

I'm helping someone who holds some Ember coin. Do you know if this coin is still alive? Or can they use their private keys in Atheneum?

Thanks

**Comment by zaemliss** [comment]
Hi, no they migrated off of Ember a very long time ago and swapped to AEM (Atheneum). 
If that person is still holding Ember, there is no way they can redeem them for Atheneum. The EMB is now useless. They missed the swap window by a year and a half.

As for Atheneum, I have no clue if this coin is still alive as I am no longer involved with it. 

Have a good one
